# Generated by Django 2.2.13 on 2022-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_auto_20220323_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
