# Generated by Django 2.2.13 on 2022-03-25 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_auto_20220323_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightApp.Passenger'),
        ),
    ]
